name: Esto es una demo
on: [push]

jobs:
  simple:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hola mundo"
        name: Hola mundo
      - name: Adiós
        run: echo "Adiós"
      - run: echo "..."  
